version: '3.8'

services:
  payload:
    image: node:22-alpine
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./media:/home/node/app/media
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile && pnpm build && pnpm start"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  node_modules:
